### ISSUE TITLE
Intermittent rustc panic when building with sccache

### ISSUE THREAD

**Issue by luser** [mozilla/sccache#122]
I had noticed previously that building large Rust projects with sccache I would occasionally get a rustc panic, but I hadn't investigated too thoroughly because it was hard to reproduce. I hit it again a few times while working on https://github.com/mozilla/sccache/issues/97 and finally got some info out. The backtrace looked like this:

<details><summary>rustc backtrace</summary><p>

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0, error_len: None }', /checkout/src/libcore/result.rs:859
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:365
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
  10: <rustc_metadata::decoder::DecodeContext<'doc, 'tcx> as serialize::serialize::Decoder>::read_str
  11: <collections::string::String as serialize::serialize::Decodable>::decode
  12: rustc_metadata::decoder::<impl rustc_metadata::cstore::MetadataBlob>::get_root
  13: rustc_metadata::locator::Context::extract_one
  14: rustc_metadata::locator::Context::find_library_crate
  15: rustc_metadata::creader::CrateLoader::load
  16: rustc_metadata::creader::CrateLoader::resolve_crate
  17: rustc_metadata::creader::CrateLoader::resolve_crate_deps::{{closure}}
  18: <collections::vec::Vec<T> as collections::vec::SpecExtend<T, I>>::spec_extend
  19: rustc_metadata::creader::CrateLoader::register_crate
  20: rustc_metadata::creader::CrateLoader::resolve_crate
  21: <rustc_metadata::creader::CrateLoader<'a> as rustc::middle::cstore::CrateLoader>::process_item
  22: rustc_resolve::build_reduced_graph::<impl rustc_resolve::Resolver<'a>>::build_reduced_graph_for_item
  23: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit::Visitor<'a>>::visit_item
  24: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit::Visitor<'a>>::visit_item
  25: rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a>>::visit_expansion
  26: syntax::ext::expand::MacroExpander::collect_invocations
  27: syntax::ext::expand::MacroExpander::expand
  28: syntax::ext::expand::MacroExpander::expand_crate
  29: rustc_driver::driver::phase_2_configure_and_expand::{{closure}}
  30: rustc_driver::driver::phase_2_configure_and_expand
  31: rustc_driver::driver::compile_input
  32: rustc_driver::run_compiler

error: Could not compile `fnv`.

Caused by:
  process didn't exit successfully: `/build/sccache2/target/debug/sccache rustc --crate-name fnv /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/fnv-1.0.5/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=fc1d5751a8057da0 -C extra-filename=-fc1d5751a8057da0 --out-dir /build/webrender/target/debug/deps -L dependency=/build/webrender/target/debug/deps --cap-lints allow` (exit code: 101)
Build failed, waiting for other jobs to finish...
ERROR:rustc_lint::builtin: span mc spanspam
ERROR:rustc_lint::builtin: span mc spanspam
ERROR:rustc_lint::builtin: span mc spanspam
error: build failed
```

</p></details>

@eddyb said this was rustc failing to read crate metadata, which is weird in this case because fnv doesn't use any extern crates. He asked me to run it again with `RUST_LOG=rustc_metadata=trace`, which produced this output:

<details><summary>rustc log messages</summary><p>

```
INFO:rustc_metadata::creader: resolving crate `extern crate std as std`
INFO:rustc_metadata::creader: falling back to a load
INFO:rustc_metadata::locator: lib candidate: /home/luser/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_unicode-f4f0ae88f5ad8ad4.rlib
INFO:rustc_metadata::locator: lib candidate: /home/luser/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-35ad9950c7e5074b.rlib
INFO:rustc_metadata::locator: lib candidate: /home/luser/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-35ad9950c7e5074b.so
INFO:rustc_metadata::locator: rlib reading metadata from: /home/luser/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_unicode-f4f0ae88f5ad8ad4.rlib
INFO:rustc_metadata::locator: reading "libstd_unicode-f4f0ae88f5ad8ad4.rlib" => Duration { secs: 0, nanos: 258457 }
INFO:rustc_metadata::locator: Rejecting via crate name
INFO:rustc_metadata::locator: metadata mismatch
INFO:rustc_metadata::locator: rlib reading metadata from: /home/luser/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-35ad9950c7e5074b.rlib
INFO:rustc_metadata::locator: reading "libstd-35ad9950c7e5074b.rlib" => Duration { secs: 0, nanos: 42329 }
INFO:rustc_metadata::creader: register crate `extern crate std as std`
INFO:rustc_metadata::creader: resolving crate `extern crate core as core`
INFO:rustc_metadata::creader: falling back to a load
INFO:rustc_metadata::locator: lib candidate: /home/luser/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-bfaa82017ca17cb2.rlib
INFO:rustc_metadata::locator: rlib reading metadata from: /home/luser/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-bfaa82017ca17cb2.rlib
INFO:rustc_metadata::locator: reading "libcore-bfaa82017ca17cb2.rlib" => Duration { secs: 0, nanos: 28230 }
INFO:rustc_metadata::creader: register crate `extern crate core as core`
INFO:rustc_metadata::creader: resolving crate `extern crate collections as collections`
INFO:rustc_metadata::creader: falling back to a load
INFO:rustc_metadata::locator: lib candidate: /home/luser/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-b479831207997444.rlib
INFO:rustc_metadata::locator: rlib reading metadata from: /home/luser/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-b479831207997444.rlib
INFO:rustc_metadata::locator: reading "libcollections-b479831207997444.rlib" => Duration { secs: 0, nanos: 92251 }
INFO:rustc_metadata::creader: register crate `extern crate collections as collections`
INFO:rustc_metadata::creader: resolving crate `extern crate core as core`
INFO:rustc_metadata::creader: resolving crate `extern crate std_unicode as std_unicode`
INFO:rustc_metadata::creader: falling back to a load
INFO:rustc_metadata::locator: lib candidate: /home/luser/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_unicode-f4f0ae88f5ad8ad4.rlib
INFO:rustc_metadata::locator: rlib reading metadata from: /home/luser/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_unicode-f4f0ae88f5ad8ad4.rlib
INFO:rustc_metadata::locator: reading "libstd_unicode-f4f0ae88f5ad8ad4.rlib" => Duration { secs: 0, nanos: 45514 }
INFO:rustc_metadata::creader: register crate `extern crate std_unicode as std_unicode`
INFO:rustc_metadata::creader: resolving crate `extern crate core as core`
INFO:rustc_metadata::creader: resolving crate `extern crate alloc as alloc`
INFO:rustc_metadata::creader: falling back to a load
INFO:rustc_metadata::locator: lib candidate: /home/luser/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_system-06d737faf6076d7c.rlib
INFO:rustc_metadata::locator: lib candidate: /home/luser/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-28913dc5a1e63cd7.rlib
INFO:rustc_metadata::locator: lib candidate: /home/luser/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-10b591f1a68dd370.rlib
INFO:rustc_metadata::locator: rlib reading metadata from: /home/luser/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-10b591f1a68dd370.rlib
INFO:rustc_metadata::locator: reading "liballoc-10b591f1a68dd370.rlib" => Duration { secs: 0, nanos: 46172 }
INFO:rustc_metadata::locator: rlib reading metadata from: /home/luser/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-28913dc5a1e63cd7.rlib
INFO:rustc_metadata::locator: reading "liballoc_jemalloc-28913dc5a1e63cd7.rlib" => Duration { secs: 0, nanos: 215436 }
INFO:rustc_metadata::locator: Rejecting via crate name
INFO:rustc_metadata::locator: metadata mismatch
INFO:rustc_metadata::locator: rlib reading metadata from: /home/luser/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_system-06d737faf6076d7c.rlib
INFO:rustc_metadata::locator: reading "liballoc_system-06d737faf6076d7c.rlib" => Duration { secs: 0, nanos: 22369 }
INFO:rustc_metadata::locator: Rejecting via crate name
INFO:rustc_metadata::locator: metadata mismatch
INFO:rustc_metadata::creader: register crate `extern crate alloc as alloc`
INFO:rustc_metadata::creader: resolving crate `extern crate core as core`
INFO:rustc_metadata::creader: resolving crate `extern crate std_unicode as std_unicode`
INFO:rustc_metadata::creader: resolving crate `extern crate alloc as alloc`
INFO:rustc_metadata::creader: resolving crate `extern crate rand as rand`
INFO:rustc_metadata::creader: falling back to a load
INFO:rustc_metadata::locator: lib candidate: /home/luser/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-20a50a22d4c2b1e9.rlib
INFO:rustc_metadata::locator: rlib reading metadata from: /home/luser/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-20a50a22d4c2b1e9.rlib
INFO:rustc_metadata::locator: reading "librand-20a50a22d4c2b1e9.rlib" => Duration { secs: 0, nanos: 48878 }
INFO:rustc_metadata::creader: register crate `extern crate rand as rand`
INFO:rustc_metadata::creader: resolving crate `extern crate core as core`
INFO:rustc_metadata::creader: resolving crate `extern crate libc as libc`
INFO:rustc_metadata::creader: falling back to a load
INFO:rustc_metadata::locator: lib candidate: /build/webrender/target/debug/deps/liblibc-b120399f12caad6d.rlib
INFO:rustc_metadata::locator: lib candidate: /home/luser/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-6ecacccb5bdc4911.rlib
INFO:rustc_metadata::locator: rlib reading metadata from: /home/luser/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-6ecacccb5bdc4911.rlib
INFO:rustc_metadata::locator: reading "liblibc-6ecacccb5bdc4911.rlib" => Duration { secs: 0, nanos: 24575 }
INFO:rustc_metadata::locator: rlib reading metadata from: /build/webrender/target/debug/deps/liblibc-b120399f12caad6d.rlib
INFO:rustc_metadata::locator: reading "liblibc-b120399f12caad6d.rlib" => Duration { secs: 0, nanos: 25319 }
error: Could not compile `bit-set`.

Caused by:
  process didn't exit successfully: `/build/sccache2/target/debug/sccache rustc --crate-name bit_set /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/bit-set-0.4.0/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=ef856a90579007dc -C extra-filename=-ef856a90579007dc --out-dir /build/webrender/target/debug/deps -L dependency=/build/webrender/target/debug/deps --extern bit_vec=/build/webrender/target/debug/deps/libbit_vec-38113c77c61ef35e.rlib --cap-lints allow` (exit code: 1)
```

</p></details>

So it's failing to read the `libc` metadata, because it's finding the wrong rlib, and it happens to be finding one that sccache is still writing out from cache. Interestingly everything in this scenario is being read from cache, there are no *real* rustc invocations, only `rustc --emit=dep-info` and `rustc --print=file-names`, but that's enough to make this happen. @eddyb suggested that I should make sccache's file writes from cache atomic and see if that makes the problem go away.

**Comment by alexcrichton** [comment]
Weird yeah this is something I'd expect the compiler to handle, but I guess it's becuase rustc itself writes these files mostly atomically rather than building them up incrementally? I'm not 100% sure about that...

> which is weird in this case because fnv doesn't use any extern crates

Ah every crate implicitly has `extern crate std`, which has its own list of dependencies.

**Comment by luser** [comment]
Yes, @eddyb indicated that this was due to a suboptimal situation in which we can't actually pass the precise paths to those dependencies, so rustc looks for them in the directory passed via `-L dependency=...`, and so it can wind up looking at arbitrary rlibs produced as part of the build.

**Comment by eddyb** [comment]
@alexcrichton Yeah I don't see any way rustc could actually handle this.... short of comparing file length? We could switch back to putting the length in the header and the absolute position of the metadata root "node" at the very end of the file, that *might* help.

**Comment by alexcrichton** [comment]
Ah yeah I think we did that awhile ago to handle this, although maybe this is being handled elsewhere?

Ideally the metadata would proclaim "I am X bytes long" and if the entire file is less than X bytes you just assume it's corrupt and ignore it (as usual)

**Comment by luser** [comment]
Yes, @eddyb indicated that this was due to a suboptimal situation in which we can't actually pass the precise paths to those dependencies, so rustc looks for them in the directory passed via `-L dependency=...`, and so it can wind up looking at arbitrary rlibs produced as part of the build.
