### ISSUE TITLE
sccache: error: thread 'tokio-runtime-worker' panicked at src/lru_disk_cache/mod.rs:204:17: Error removing file from cache: 

### ISSUE THREAD

**Issue by dabrahams** [mozilla/sccache#2092]
In [this build](https://github.com/hylo-lang/llvm-build/actions/runs/7895297454/job/21547584509#step:14:2546), sccache freaked out as follows, only on macos (full logs:
[5_distribution (macos-latest, amd64).txt](https://github.com/mozilla/sccache/files/14275159/5_distribution.macos-latest.amd64.txt)
[6_distribution (macos-latest, arm64).txt](https://github.com/mozilla/sccache/files/14275160/6_distribution.macos-latest.arm64.txt)

You can reproduce by forking that project at 90b9e81 and manually triggering the workflow
```
sccache: encountered fatal error
sccache: error: thread 'tokio-runtime-worker' panicked at src/lru_disk_cache/mod.rs:204:17: Error removing file from cache: `"/Users/runner/work/llvm-build/llvm-build/.sccache/preprocessor/7/d/5/7d553347d23a053780beb2e6cc81746db44ea0eee6b9ee645fc2bb29a43d8c4c"`: failed to remove file `/Users/runner/work/llvm-build/llvm-build/.sccache/preprocessor/7/d/5/7d553347d23a053780beb2e6cc81746db44ea0eee6b9ee645fc2bb29a43d8c4c`
sccache: caused by: thread 'tokio-runtime-worker' panicked at src/lru_disk_cache/mod.rs:204:17: Error removing file from cache: `"/Users/runner/work/llvm-build/llvm-build/.sccache/preprocessor/7/d/5/7d553347d23a053780beb2e6cc81746db44ea0eee6b9ee645fc2bb29a43d8c4c"`: failed to remove file `/Users/runner/work/llvm-build/llvm-build/.sccache/preprocessor/7/d/5/7d553347d23a053780beb2e6cc81746db44ea0eee6b9ee645fc2bb29a43d8c4c`
...
sccache: encountered fatal error
sccache: error: thread 'tokio-runtime-worker' panicked at src/cache/disk.rs:180:14: called `Result::unwrap()` on an `Err` value: PoisonError { .. }
sccache: caused by: thread 'tokio-runtime-worker' panicked at src/cache/disk.rs:180:14: called `Result::unwrap()` on an `Err` value: PoisonError { .. }
...
ache: encountered fatal error
sccache: error: thread 'tokio-runtime-worker' panicked at src/cache/disk.rs:180:14: called `Result::unwrap()` on an `Err` value: PoisonError { .. }
sccache: caused by: thread 'tokio-runtime-worker' panicked at src/cache/disk.rs:180:14: called `Result::unwrap()` on an `Err` value: PoisonError { .. }
```

**Comment by LucasSte** [comment]
I'm facing the exact same problem. I hope someone investigates thi.

**Comment by sylvestre** [comment]
Please provide a small test case which demonstrates the issue.

**Comment by dabrahams** [comment]
Well that would be nice wouldn't it?  But since Tokio is concerned with threading the odds are high that this is a nondeterministic behavior, and only reproduces with large projects. I changed my project a little and the issue went away. 

You're not going to get a small reproducer by asking for it, I wager.  I think you should design a threading stress test and run it on macOS with thread sanitizer.

**Comment by dabrahams** [comment]
Seems unlikely since e it happens on a GitHub runner and only sometimes

**Comment by expipiplus1** [comment]
FWIW, I've bumped into this on OSX and Linux runners building LLVM too, both clang and gcc https://github.com/shader-slang/slang/actions/runs/8627564984/job/23650460259?pr=3703

**Comment by kendalharland** [comment]
I have observing this same behavior on GitHub runners for The Bowser Company's swift toolchain builds.

**Comment by kendalharland** [comment]
In my case, I am using sccache through the Github action at `hendrikmuhs/ccache-action`.  This action creates GitHub caches using a user-supplied key. It seems that those caches became corrupted, and clearing them has resolved this issue for me. I have yet to determine if this is a bug in sccache, or the above action, or a bug at all.

**Comment by ahayzen-kdab** [comment]
We've also hit this issue in our CI, adding some tracing to the panic in the lru_cache where it tries to remove the file shows that it is attempting to remove a file that is "NotFound".

What I believe is happening is

- The cache maximum size has been reached
- Multiple tasks start attempting to remove old entries from the cache
- Different tasks end up trying to remove the same entry
- First wins, second fails

I've pushed a change while resolves the issue in our CI so far, it simply ignores any NotFound errors and moves onto the next file. https://github.com/mozilla/sccache/pull/2334

When observing the logs of a now successful run i can see that it tries to remove 125 files that are NotFound, then when i check the hashes the files that are NotFound did exist before in the LRU cache. So it appears that two jobs have picked the same entries.

**Comment by kendalharland** [comment]
Thank You!
