### ISSUE TITLE
fail to run sccache with memcached

### ISSUE THREAD

**Issue by glehmann** [mozilla/sccache#417]
the sccache server is crashing when I try to use it with memcached:

~~~~
> env SCCACHE_START_SERVER=1 SCCACHE_NO_DAEMON=1 RUST_LOG=debug SCCACHE_MEMCACHED=tcp://localhost RUST_BACKTRACE=full sccache
DEBUG 2019-04-25T15:54:39Z: sccache::config: Attempting to read config file at "/home/glehmann/.config/sccache/config"
DEBUG 2019-04-25T15:54:39Z: sccache::config: Couldn't open config file: No such file or directory (os error 2)
 INFO 2019-04-25T15:54:39Z: sccache::server: start_server: port: 4226
 INFO 2019-04-25T15:54:39Z: jobserver::imp: created a jobserver: Client { read: File { fd: 3, path: "pipe:[23672482]", read: true, write: false }, write: File { fd: 4, path: "pipe:[23672482]", read: false, write: true } }
DEBUG 2019-04-25T15:54:39Z: sccache::cache::cache: Trying Memcached(tcp://localhost)
 INFO 2019-04-25T15:54:39Z: sccache::server: server started, listening on port 4226
DEBUG 2019-04-25T15:54:45Z: sccache::server: handle_client: compile
DEBUG 2019-04-25T15:54:45Z: tokio_reactor: dropping I/O source: 2
DEBUG 2019-04-25T15:54:45Z: tokio_reactor: dropping I/O source: 3
DEBUG 2019-04-25T15:54:45Z: sccache::compiler::compiler: Found GCC
DEBUG 2019-04-25T15:54:45Z: sccache::server: check_compiler: Supported compiler
DEBUG 2019-04-25T15:54:45Z: sccache::server: parse_arguments: Ok: [...many gcc options removed... "-c", "../Lib/Configuration/ConfigurationUtil.cxx"]
DEBUG 2019-04-25T15:54:45Z: sccache::compiler::compiler: [ConfigurationUtil.cxx.o]: get_cached_or_compile: [...many gcc options removed... "-c", "../Lib/Configuration/ConfigurationUtil.cxx"]
DEBUG 2019-04-25T15:54:46Z: tokio_reactor: dropping I/O source: 3
DEBUG 2019-04-25T15:54:46Z: tokio_reactor: dropping I/O source: 2
DEBUG 2019-04-25T15:54:46Z: tokio_reactor: dropping I/O source: 4
DEBUG 2019-04-25T15:54:46Z: sccache::compiler::compiler: [ConfigurationUtil.cxx.o]: generate_hash_key took 0.584 s
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: StringError("invalid socket address") }', src/libcore/result.rs:1009:5
stack backtrace:
   0:           0xb600e3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h508e385542e74f0f
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:           0xb5a058 - std::sys_common::backtrace::_print::h0654a4145b8e108e
                               at src/libstd/sys_common/backtrace.rs:71
   2:           0xb5e922 - std::panicking::default_hook::{{closure}}::h9d3b4aa9777cceab
                               at src/libstd/sys_common/backtrace.rs:59
                               at src/libstd/panicking.rs:211
   3:           0xb5e68d - std::panicking::default_hook::h54bc90cfc6073aee
                               at src/libstd/panicking.rs:227
   4:           0xb5f030 - std::panicking::rust_panic_with_hook::h28b9ce6fa7a5033b
                               at src/libstd/panicking.rs:491
   5:           0xb5ebb1 - std::panicking::continue_panic_fmt::h4c221b9431554bc2
                               at src/libstd/panicking.rs:398
   6:           0xb5ea95 - rust_begin_unwind
                               at src/libstd/panicking.rs:325
   7:           0xb91e3c - core::panicking::panic_fmt::h4d67173bc68f6d5a
                               at src/libcore/panicking.rs:95
   8:           0x450a19 - core::result::unwrap_failed::h7e94966fa8463944
   9:           0x570a84 - <std::thread::local::LocalKey<T>>::with::hd9e309753aea199d
  10:           0x584386 - <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll::h2e2891d11d397e9c
  11:           0x4ddcf0 - std::panicking::try::do_call::he3b6e8562370eee2
  12:           0xb71009 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:102
  13:           0x6640ba - <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll::hecbc108878a20d2f
  14:           0x6859a3 - <futures_cpupool::MySender<F, core::result::Result<<F as futures::future::Future>::Item, <F as futures::future::Future>::Error>> as futures::future::Future>::poll::h523f329221981159
  15:           0xa4a36e - futures::task_impl::std::set::hd5b75808dbfc07f8
  16:           0xa4a4ce - futures::task_impl::std::Run::run::h6f128156eddb70c4
  17:           0xa41c46 - futures_cpupool::Inner::work::hffea4e3fd75fa6f2
  18:           0xa42b99 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd363e3113432bf01
  19:           0xa432f4 - std::panicking::try::do_call::h7408e14d8ba4d73b
  20:           0xb71009 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:102
  21:           0xa43135 - <F as alloc::boxed::FnBox<A>>::call_box::h1b975af12fa9607d
  22:           0xb6890d - std::sys::unix::thread::Thread::new::thread_start::hfe243d0f561ae5cd
                               at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/liballoc/boxed.rs:683
                               at src/libstd/sys_common/thread.rs:24
                               at src/libstd/sys/unix/thread.rs:90
DEBUG 2019-04-25T15:54:46Z: tokio_reactor: dropping I/O source: 0
DEBUG 2019-04-25T15:54:46Z: tokio_reactor: dropping I/O source: 1
~~~~

my setup is quite simple:

~~~
docker run --name memcached-sccache -p11211:11211 --restart always -d memcached
env SCCACHE_MEMCACHED=tcp://localhost cmake  -G Ninja -D CMAKE_C_COMPILER_LAUNCHER=sccache -D CMAKE_CXX_COMPILER_LAUNCHER=sccache ..
env SCCACHE_MEMCACHED=tcp://localhost ninja -j1
~~~~

sccache works properly with a file cache, and the statistics seem to be ok:

~~~~
> env SCCACHE_MEMCACHED=tcp://localhost sccache -s
Compile requests                          0
Compile requests executed                 0
Cache hits                                0
Cache misses                              0
Cache timeouts                            0
Cache read errors                         0
Forced recaches                           0
Cache write errors                        0
Compilation failures                      0
Cache errors                              0
Non-cacheable compilations                0
Non-cacheable calls                       0
Non-compilation calls                     0
Unsupported compiler calls                0
Successful distributed compilations       0
Failed distributed compilations           0
Average cache write                   0.000 s
Average cache read miss               0.000 s
Average cache read hit                0.000 s
Cache location                      Memcached: tcp://localhost
~~~~

any idea of what may have gone wrong?

**Comment by luser** [comment]
It's not totally clear but [the docs](https://github.com/mozilla/sccache#memcached) do mention that this needs to be `tcp://host:port`. You're missing a port in your configuration. It would be nice if this produced a clearer error message.
