### ISSUE TITLE
0.2.14 with Redis: tokio there is no reactor running

### ISSUE THREAD

**Issue by deimosfr** [mozilla/sccache#915]
Hi,

I'm experiencing an issue with 0.2.14 with Redis. On 0.2.13 it works well.

Here is the issue:
```
root@99a9eaa4b5ef:/# export RUSTC_WRAPPER=/usr/bin/sccache
root@99a9eaa4b5ef:/# export SCCACHE_REDIS=redis://192.168.0.50:6379/
root@99a9eaa4b5ef:/# SCCACHE_LOG_LEVEL=trace RUST_BACKTRACE=full SCCACHE_NO_DAEMON=1 sccache -s
thread 'main' panicked at 'there is no reactor running, must be called from the context of Tokio runtime', /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.6/src/io/driver/mod.rs:263:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::option::expect_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1226
   3: tokio::io::driver::Handle::current
   4: tokio::io::poll_evented::PollEvented<E>::new
   5: tokio::net::tcp::stream::TcpStream::new
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll
  10: futures::future::join::MaybeDone<A>::poll
  11: <futures::future::join::Join<A,B> as futures::future::Future>::poll
  12: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  13: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  14: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  15: <futures::stream::and_then::AndThen<S,F,U> as futures::stream::Stream>::poll
  16: <futures::stream::flatten::Flatten<S> as futures::stream::Stream>::poll
  17: <futures::stream::forward::Forward<T,U> as futures::future::Future>::poll
  18: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  19: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  20: futures::task_impl::std::set
  21: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  22: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  23: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  24: tokio::runtime::task::harness::Harness<T,S>::poll
  25: std::thread::local::LocalKey<T>::with
  26: tokio::task::local::LocalSet::tick
  27: tokio::macros::scoped_tls::ScopedKey<T>::set
  28: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  29: tokio::macros::scoped_tls::ScopedKey<T>::set
  30: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
  31: tokio::runtime::context::enter
  32: std::thread::local::LocalKey<T>::with
  33: std::thread::local::LocalKey<T>::with
  34: sccache::server::start_server
  35: sccache::commands::run_command
  36: sccache::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
sccache: error: failed to get stats from server
sccache: caused by: Failed to send data to or receive data from server
sccache: caused by: Failed to read response header
sccache: caused by: failed to fill whole buffer
```

Steps to reproduce with a Dockerfile:
```
FROM rust:latest

# Verify Cargo location.
RUN echo 'Verifying Cargo location...' && \
    [ -d '/usr/local/cargo' ]

# Install sccache.
RUN echo 'Installing sccache...' && \
    mkdir -p /opt/sccache/ && \
    cd /opt/sccache/ && \
    wget 'https://github.com/mozilla/sccache/releases/download/0.2.14/sccache-0.2.14-x86_64-unknown-linux-musl.tar.gz' && \
    wget 'https://github.com/mozilla/sccache/releases/download/0.2.14/sccache-0.2.14-x86_64-unknown-linux-musl.tar.gz.sha256' && \
    echo 'Verifying checksum...' && \
    echo "$(cat sccache-0.2.14-x86_64-unknown-linux-musl.tar.gz.sha256) sccache-0.2.14-x86_64-unknown-linux-musl.tar.gz" | sha256sum --check && \
    echo 'Extracting prebuilt binary...' && \
    tar -xvzf sccache-0.2.14-x86_64-unknown-linux-musl.tar.gz --strip-components 1 && \
    rm sccache-0.2.14-x86_64-unknown-linux-musl.tar.gz && \
    rm sccache-0.2.14-x86_64-unknown-linux-musl.tar.gz.sha256 && \
    ln -s /opt/sccache/sccache /usr/local/bin/sccache && \
    echo 'Verifying installation...' && \
    sccache --version

# Update registry index.
ARG CACHE_KEY
RUN echo 'Updating registry index...' && \
    echo "CACHE_KEY=$CACHE_KEY" && \
    cargo search --verbose --limit 0
```

If I change with 0.2.13, it works well:
```
root@b52003135daf:/# export RUSTC_WRAPPER=/usr/bin/sccache
root@b52003135daf:/# export SCCACHE_REDIS=redis://192.168.0.50:6379/
root@b52003135daf:/# SCCACHE_LOG_LEVEL=trace RUST_BACKTRACE=full SCCACHE_NO_DAEMON=1 sccache -s
Compile requests                      0
Compile requests executed             0
Cache hits                            0
Cache misses                          0
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Compilation failures                  0
Cache errors                          0
Non-cacheable compilations            0
Non-cacheable calls                   0
Non-compilation calls                 0
Unsupported compiler calls            0
Average cache write               0.000 s
Average cache read miss           0.000 s
Average cache read hit            0.000 s
Failed distributed compilations       0
Cache location                  Redis: redis://192.168.0.50:6379/
Cache size                          190 MiB
```

Any help would be appreciate.

Thanks

**Comment by glandium** [comment]
Can you test 46d51c1404684e5c051ed0cec8ff96410eff806f? If that also doesn't work, can you test 2b083d1a4d2da2e0d2382512df3cea04fcb575b5?

**Comment by glandium** [comment]
Forget it, I validated it works with https://github.com/mozilla/sccache/commit/46d51c1404684e5c051ed0cec8ff96410eff806f
